"""delete password  db

Revision ID: f3a0a76b237c
Revises: c4b530430f89
Create Date: 2024-04-11 22:15:51.889005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a0a76b237c'
down_revision = 'c4b530430f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_column('expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', mysql.DATETIME(), nullable=False))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
